### ISSUE TITLE
Add jobs to CI pipelines

### ISSUE THREAD

**Issue by marcoshuck** [nbortolotti/tflitego#16]
In order to improve our pipeline execution, it would be nice to add different jobs running the following commands:

## Format
- `go fmt ./...`

## Vet
Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string. Vet uses heuristics that do not guarantee all reports are genuine problems, but it can find errors not caught by the compilers.
- `go vet -v ./...`

## Tests
- `go test -v ./...`

## Race conditions
- `go test -v -race`

## Coverage
- `go test -v -covermode=atomic -coverprofile=coverage.tx ./...`
- `go tool cover -func=coverage.tx`

**Comment by nbortolotti** [comment]
Can we considered solved with last PR #20 ? there it's not implemented race conditions. Thoughts?

**Comment by nbortolotti** [comment]
Added all the suggested elements into current [go.yml](https://github.com/nbortolotti/tflitego/blob/main/.github/workflows/go.yml) execution. Feel free to re open if something is missing.
