### ISSUE TITLE
A package for simplified use of the Tensorflow API is not available

### ISSUE THREAD

**Issue by vovasilenko** [nbortolotti/tflitego#28]
Unfortunately not available: https://storage.googleapis.com/clitelibrary/ctflitelib_2.4.0.tar.gz

**Comment by nbortolotti** [comment]
@Nenteru yep, I removed some datastorage files and I made and I made a mistake of not replacing this link.  Here the library. apologies!
[ctflitelib_2.4.0.tar.gz](https://github.com/user-attachments/files/17504902/ctflitelib_2.4.0.tar.gz)

**Comment by vovasilenko** [comment]
@nbortolotti Thank you very much for such a quick response! 

It will be great if other versions can be downloaded using the link: 
wget https://storage.googleapis.com/clitelibrary/ctflitelib_ [version].tar.gz

And it would also be great if libraries for Raspberry Pi were available. (I need them more) ^^

**Comment by nbortolotti** [comment]
@Nenteru  I have a created a version for Raspberry. 
[ctflitelib_2.4.0_ARMv7.tar.gz](https://github.com/user-attachments/files/17524421/ctflitelib_2.4.0_ARMv7.tar.gz)

Yep muti version is a great idea, unfortunality We don´t have communicty traction to support more assets but it could be in the future :)

**Comment by nbortolotti** [comment]
I will close it because I'm assuming it was useful and solved.
