### ISSUE TITLE
Rename package name from tflitego to tflite

### ISSUE THREAD

**Issue by marcoshuck** [nbortolotti/tflitego#5]
It might be a good idea to rename `tflitego` to just `tflite`.

Now:
```go
	model, err := tflitego.NewTFLiteModelFromFile("iris_lite.tflite")
```

After applying this change:
```go
	model, err := tflite.NewTFLiteModelFromFile("iris_lite.tflite")
```

**Comment by nbortolotti** [comment]
could be a good idea, I added a discussion to explore the case and brainstorm but I imagine the objective is provide more clear approach ...or is there  a restriction to composite a go words into the package name?

https://blog.golang.org/package-names

**Comment by marcoshuck** [comment]
Hey @nbortolotti thanks for replying... This isn't a restriction per se, just wondering if it adds any value to have the `go` word in a `go package`, that's it. The reason why I'm proposing this right now is because if people start using this library in the near future, it'll be too late.

**Comment by nbortolotti** [comment]
Following our [Discussion #10](https://github.com/nbortolotti/tflitego/discussions/10) , we can maintain the name of the repository and change the package name to tflite.
